[package]
name = "tinyraytracer"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[dependencies]
nalgebra = "0.17.0"
png = "0.14.0"
jpeg-decoder = "0.1.15"

[[bin]]
name = "kaboom"
path = "src/kaboom.rs"

[[bin]]
name = "raytracer"
path = "src/raytracer.rs"
